<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "xeniathiem_semps"
 *
 * Auto generated by Extension Builder 2021-05-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Xenia Thiem Semps',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Xenia Thiem',
    'author_email' => 'xt@xeniathiem.de',
    'state' => 'alpha',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
